INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('1','Papatya Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('2','Sas Biliþim Yayýnlarý')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('3','Litaratür Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('4','Palme Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('5','KODLAB')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('6','Beta Basým Yayýn')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('7','Akademi Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('8','Pusula Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('9','DaisyScience Int Pub')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('10','Dikeyeksen Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('11','Nobel Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('12','Çaðlayan Kitapevi')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('13','Umuttepe Yayýnlarý')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('14','Siyasal Kitapevi')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('15','Orion Kitapevi')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('16','Seçkin Yayýncýlýk')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('17','Gazi Kitapevi')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('18','Ekin Basýn Yayýn')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('19','Birsen Yayýnevi')
INSERT INTO dbo.publisher ([publisher_no],[name]) VALUES ('20','ODTÜ Yyýncýlýk')