INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Papatya Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Sas Bilişim Yayınları');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Litaratür Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Palme Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('KODLAB');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Beta Basım Yayın');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Akademi Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Pusula Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('DaisyScience Int Pub');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Dikeyeksen Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Nobel Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Çağlayan Kitapevi');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Umuttepe Yayınları');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Siyasal Kitapevi');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Orion Kitapevi');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Seçkin Yayıncılık');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Gazi Kitapevi');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Ekin Basın Yayın');
INSERT INTO `kitapevi`.`publisher` (`name`) VALUES ('Birsen Yayınevi');