INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('1', 'Bilgisayar Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('2', 'Çevre Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('3', 'Elektrik-Elektronik Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('4', 'Endüstri Mühendisliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('5', 'Gýda Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('6', 'Harita Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('7', 'Kimya Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('8', 'Makina Mühendsiliði')
INSERT INTO dbo.department ([department_no], [departmentname]) VALUES ('9', 'Malzeme Bilimleri Mühendsiliði')