INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('1', 'Aðlar')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('2', 'Bilgisayar Donanýmlarý')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('3', 'Yazýlým Güvenliði')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('4', 'Veritabanlarý')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('5', 'Ýþletim Sistemleri')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('6', 'Programlama')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('7', 'Ýnþaat Bilimleri')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('8', 'Çevre Bilimleri')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('9', 'Elektronik')
INSERT INTO dbo."subject" ([subject_no],[stitle]) VALUES ('10', 'Enerji')
