INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Bilgisayar Ağları ve İnternet Mühendisliği','Rıfat Çölkesen','2013-01-01','25','1','1');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Bilgisayar Haberleşmesi ve Ağ Teknolojileri','Rıfat Çölkesen','2013-01-01','35','1','1');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Bilgisayar Ağları','Demir Öner','2010-01-01','35','1','1');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Network TCP/IP UNIX El Kitabı','Rıfat Çölkesen','2012-01-01','25','1','1');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Bilgisayar Ağları','Nazife Baykal','2005-01-01','40','2','1');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Bilgisayar Sistemleri Mimarisi','Moris Mano','2002-01-01','35','3','2');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Her Yönüyle FPGA ve VHDL','Engin Sarıtaş','2012-01-01','48','4','2');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Lojik Devre Tasarımı','Rıfat Çölkesen','2012-01-01','35','1','2');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Backtrack 5 R3 ve Penetrasyon Testleri','Özkan Bozkurt','2014-01-01','26','5','3');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Veri Gizleme','Feyzi Akar','2014-01-01','39','6','3');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Ağ ve Yazılım Güvenliği','Furkan Çontar','2013-01-01','23','5','3');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Hacking Interface','Hamza ElBahadır','2010-01-01','25','5','3');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('10 Adımla Bilgisayar Güvenliği','Uğur Gelişken','2009-01-01','21','5','3');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('T-SQL & SQL SERVER 2012','Hamza Elbahadır','2010-01-01','27','5','4');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('SQL SERVER 2008 R2','Selçuk Özdemir','2010-01-01','27','5','4');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Veri Tabanı Sistemleri','Ünal Yarımağan','2010-01-01','39','7','4');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Oracle Database 11g R2','Talip Hakan Öztürk','2014-01-01','55','8','4');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Ubuntu Kolay.Güvenilir.Hızlı ve Ücretsiz!','Atalay Keleştem','2011-01-01','25','5','5');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Pardus 2011','Atalaj Keleştem','2011-01-01','20','5','5');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Gömülü Linux Sistemleri','Nazım Koç','2013-01-01','56','8','5');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Gömülü Sistem Tasarımı','Deniz Taşkın','2012-01-01','17','1','5');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('C Programlama Dili','Rıfat Çölkesen','2012-01-01','25','9','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('C# Programlama Dili ve Yazılım Tasarımı','Ahmet Kaymaz','2013-01-01','35','1','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('JSP','Numan Pekgöz','2013-01-01','35','8','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Java Nesne Yönelimli Programlama','Ali Orhan Aydın','2012-01-01','30','8','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Java Programlama Dili ve Yazılım Tasarımı','Altuğ B. Altıntaş','2014-01-01','39','1','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('HTML 5 & CSS 3','Fahrettin Erdinç','2014-01-01','30','8','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('C ile Bilgisayar Programlamaya Giriş','Ali Orhan Aydın','2014-01-01','35','8','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Java 8','A.Kerim Fırat','2013-01-01','38','5','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Ruby','Sıtkı Bağdat','2013-01-01','30','10','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Yeni Başlayanlar için Java','Mehmet Kirazlı','2012-01-01','38','5','6');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Statik','Etimad Eyvazov','2014-01-01','18','11','7');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Kırılma Mekaniği','Paşa Yayla','2007-01-01','18','12','7');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Zemin Mekanik Problemleri','Fazıl Kip','1999-01-01','25','12','7');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Akışkan Mekaniği Hidrolik','Nuri Yücel','2001-01-01','30','11','7');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Hava Kalitesi Yöntemi','H.Hüseyin Öztürk','2012-01-01','30','13','8');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Sosyal Çevre Bilimleri','Hakan Reyhan','2014-01-01','32','14','8');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Çevre ve Kalkınma Söylemi','Murat Kayıkçı','2012-01-01','15','13','8');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Kent Ekolojisi','Latif Kurt','2015-01-01','27','4','8');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Güç Elektroniği','Muhammed H. Rasim','2015-01-01','50','11','9');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Kontrol Sistemleri Analizi ve Tasarımı','Muammer Gürbucak','2014-01-01','36','16','9');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Yakıt Pili Teknolojisi','H.Hüseyin Öztürk','2012-01-01','13','13','10');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Isı Transferi','J.P.Holman','2014-01-01','50','11','13');
INSERT INTO `kitapevi`.`book` (`name`,`first-author`,`year`,`price`,`publisher_no`,`subject_no`) VALUES ('Yenilebilir Enerji Kaynakları','H.Hüseyin Öztürk','2013-01-01','35','19','13');
